name: Build mouse.c

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    strategy:
      matrix:
        arch: [x64, x86, arm64, arm]
        compiler: [gcc, clang]
        exclude:
          - arch: arm64
            compiler: clang
          - arch: arm
            compiler: clang
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib
          echo "CC=gcc" >> $GITHUB_ENV
        else
          sudo apt-get update
          sudo apt-get install clang
          echo "CC=clang" >> $GITHUB_ENV
        fi

    - name: Build for ${{ matrix.arch }}
      run: |
        # Set architecture-specific flags
        case "${{ matrix.arch }}" in
          x64)
            CFLAGS=""
            ;;
          x86)
            CFLAGS="-m32"
            ;;
          arm64)
            sudo apt-get install gcc-aarch64-linux-gnu
            export CC=aarch64-linux-gnu-gcc
            ;;
          arm)
            sudo apt-get install gcc-arm-linux-gnueabihf
            export CC=arm-linux-gnueabihf-gcc
            ;;
        esac

        $CC $CFLAGS mouse.c -o mouse-${{ matrix.arch }}-${{ matrix.compiler }} -lm

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-${{ matrix.arch }}-${{ matrix.compiler }}
        path: mouse-${{ matrix.arch }}-${{ matrix.compiler }}

  build-macos:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build for ${{ matrix.arch }}
      run: |
        # Set architecture flag
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          ARCH_FLAGS="-arch arm64"
        else
          ARCH_FLAGS="-arch x86_64"
        fi

        clang $ARCH_FLAGS mouse.c -o mouse-${{ matrix.arch }} -lm

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.arch }}
        path: mouse-${{ matrix.arch }}

  build-windows:
    strategy:
      matrix:
        compiler: [msvc, mingw]
        arch: [x64, x86]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build with MSVC
      if: matrix.compiler == 'msvc'
      run: |
        cl mouse.c /Fe:mouse-${{ matrix.arch }}-msvc.exe
      shell: cmd

    - name: Setup MinGW
      if: matrix.compiler == 'mingw'
      run: choco install mingw -y

    - name: Build with MinGW
      if: matrix.compiler == 'mingw'
      run: |
        if "${{ matrix.arch }}" == "x86" (
          set CFLAGS=-m32
        )
        gcc %CFLAGS% mouse.c -o mouse-${{ matrix.arch }}-mingw.exe -lm
      shell: cmd

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.arch }}-${{ matrix.compiler }}
        path: mouse-${{ matrix.arch }}-${{ matrix.compiler }}.exe

  build-android:
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86, x86_64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build for Android ${{ matrix.arch }}
      run: |
        # Set target based on architecture
        case "${{ matrix.arch }}" in
          arm64-v8a)
            TARGET=aarch64-linux-android
            ;;
          armeabi-v7a)
            TARGET=armv7a-linux-androideabi
            ;;
          x86)
            TARGET=i686-linux-android
            ;;
          x86_64)
            TARGET=x86_64-linux-android
            ;;
        esac

        CLANG_PATH=$(find $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin -name "$TARGET*-clang" | head -1)

        $CLANG_PATH --target=$TARGET mouse.c -o mouse-android-${{ matrix.arch }} -lm

    - name: Upload Android artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-${{ matrix.arch }}
        path: mouse-android-${{ matrix.arch }}
