name: Build mouse.c

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    strategy:
      matrix:
        arch: [x64, x86]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install X11 dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxtst-dev

    - name: Build for ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.arch }}" = "x86" ]; then
          sudo apt-get install -y gcc-multilib
          CFLAGS="-m32"
        fi
        gcc $CFLAGS mouse.c -o mouse-linux-${{ matrix.arch }} -lX11 -lXtst -lm

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-${{ matrix.arch }}
        path: mouse-linux-${{ matrix.arch }}

  build-macos:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build for ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          ARCH_FLAGS="-arch arm64"
        else
          ARCH_FLAGS="-arch x86_64"
        fi

        clang $ARCH_FLAGS mouse.c -o mouse-macos-${{ matrix.arch }} -framework CoreGraphics -framework CoreFoundation -framework IOKit

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.arch }}
        path: mouse-macos-${{ matrix.arch }}

  build-windows:
    strategy:
      matrix:
        arch: [x64, x86]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/setup-msvc@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Build with MSVC
      run: cl mouse.c /Fe:mouse-windows-${{ matrix.arch }}.exe user32.lib gdi32.lib
      shell: cmd

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.arch }}
        path: mouse-windows-${{ matrix.arch }}.exe

  build-android:
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build for Android ${{ matrix.arch }}
      run: |
        case "${{ matrix.arch }}" in
          arm64-v8a)
            TARGET=aarch64-linux-android
            API=21
            ;;
          armeabi-v7a)
            TARGET=armv7a-linux-androideabi
            API=16
            ;;
        esac

        $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/${TARGET}${API}-clang mouse.c -o mouse-android-${{ matrix.arch }} -lm

    - name: Upload Android artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-${{ matrix.arch }}
        path: mouse-android-${{ matrix.arch }}
