name: Build Mouse Mover

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86, x86_64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxtst-dev clang gcc-multilib

    - name: Build for Linux ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.arch }}" = "x86" ]; then
          clang -m32 -o mouse-linux-x86 mouse.c -lX11 -lXtst -Os -s
        else
          clang -m64 -o mouse-linux-x86_64 mouse.c -lX11 -lXtst -Os -s
        fi

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: mouse-linux-${{ matrix.arch }}
        path: mouse-linux-${{ matrix.arch }}

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build for macOS ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          clang -o mouse-macos-arm64 mouse.c -framework ApplicationServices -Os -s -arch arm64
        else
          clang -o mouse-macos-x86_64 mouse.c -framework ApplicationServices -Os -s -arch x86_64
        fi

    - name: Upload macOS binary
      uses: actions/upload-artifact@v4
      with:
        name: mouse-macos-${{ matrix.arch }}
        path: mouse-macos-${{ matrix.arch }}

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x86_64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build for Windows ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.arch }}" = "x86" ]; then
          cl mouse.c /link user32.lib /O2 /Fe:mouse-windows-x86.exe
        else
          cl mouse.c /link user32.lib /O2 /Fe:mouse-windows-x86_64.exe
        fi

    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: mouse-windows-${{ matrix.arch }}
        path: mouse-windows-${{ matrix.arch }}.exe

  create-release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*
