name: Build Mouse Mover with Clang

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: mouse-linux
          - os: macos-latest
            artifact_name: mouse-macos
          - os: windows-latest
            artifact_name: mouse.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Clang on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libx11-dev libxtst-dev

    - name: Build on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        clang -o mouse mouse.c -lX11 -lXtst -Os -s
        strip mouse

    - name: Build on macOS
      if: matrix.os == 'macos-latest'
      run: |
        clang -o mouse mouse.c -framework ApplicationServices -Os -s

    - name: Set up Clang on Windows
      if: matrix.os == 'windows-latest'
      uses: llvm/actions/setup-llvm@v1
      with:
        version: 'latest'

    - name: Build on Windows
      if: matrix.os == 'windows-latest'
      run: |
        clang mouse.c -luser32 -O2 -o mouse.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: mouse*
